name: called workflow

on:
  workflow_dispatch:
    inputs:
      something: 
        description: "the auto approve GitHub token"
        required: true
        type: string

jobs:
  verify:
    environment: dummy
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars (SIT enabled)
        shell: bash
        run: |
          echo $REF
          echo 
        env: 
          REF: ${{ github.ref}} 
          TEST: ${{ inputs.something }}