name: Caliing workflow

on:
  push:

jobs:
  verify:
    uses: og-test-org/some-test/.github/workflows/called-workflow.yml@main
      # - uses: convictional/trigger-workflow-and-wait@v1.6.1
      #   with:
      #     owner: og-test-org
      #     repo: some-test
      #     github_token: ${{ secrets.GITHUBTOKEN }}
      #     workflow_file_name: called-workflow.yaml
        