name: called workflow

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          if [[ github.actor != 'github-actions[bot]' ]]; then 
            echo "not github-actions[bot]"
            exit 1;
          fi 
          echo "$GITHUB_CONTEXT"