name: called workflow

on:
  workflow_dispatch:
    inputs:
      token: 
        description: "the auto approve GitHub token"
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          # if [[ ${{ github.sender.login }} != 'james-ogunsanwo' ]]; then 
          # echo "${{ github.sender.login }}"
          #   echo "not github-actions[bot]"
          #   exit 1;
          # fi 
          echo "$GITHUB_CONTEXT"
          echo ${{ inputs.token }}