name: Click test

on:
  workflow_dispatch:
    inputs:
      TEAM_NAME:
        description: "Your team name to use for the file containing secrets e.g. production-engineering"
        required: true
      SECRET_NAME:
        description: "The name of the secret"
        required: true
      SECRET_VALUE:
        description: "The value of the secret to be encrypted"
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask input
        shell: bash
        run: |
          # INP_SECRET=$(jq -r '.inputs.SECRET_VALUE' $GITHUB_EVENT_PATH)
          # echo ::add-mask::$INP_SECRET
          # echo SECRET_VALUE="$INP_SECRET" >> $GITHUB_ENV

          jq -r '.inputs.SECRET_VALUE' $GITHUB_EVENT_PATH > key.txt
          while read -r line;
          do
            echo "::add-mask::${line}"
          done < key.txt
          
          echo "ssh_key<<EOF" >> $GITHUB_OUTPUT
          cat key.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "HIT"

          echo SECRET_VALUE=$(echo key.txt) >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: |
              echo ${{ github.event.inputs.TEAM_NAME }} >> test.txt
              echo ${{ github.event.inputs.SECRET_NAME }} >> test.txt
              echo ${{ github.event.inputs.SECRET_VALUE }} >> test.txt
              git config --global user.email "$TRIGGERING_USER@users.noreply.github.com"
              git config --global user.name "$TRIGGERING_USER"
              git add test.txt
              git commit -m "adding stuff"
              git push --set-upstream origin main
        env:
          TEAM_NAME: ${{ github.event.inputs.TEAM_NAME }}
          SECRET_NAME: ${{ github.event.inputs.SECRET_NAME }}
          SECRET_VALUE: ${{ github.event.inputs.SECRET_VALUE }}
