name: Click test

on:
  workflow_dispatch:
    inputs:
      TEAM_NAME:
        description: "Your team name to use for the file containing secrets e.g. production-engineering"
        required: true
      SECRET_NAME:
        description: "The name of the secret"
        required: true
      SECRET_VALUE:
        description: "The value of the secret to be encrypted"
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask input
        shell: bash
        run: |
          jq -r '.inputs.SECRET_VALUE' $GITHUB_EVENT_PATH > secret.txt
          while read -r line;
          do
            echo "::add-mask::${line}"
          done < secret.txt
          
          echo "secret<<EOF" >> $GITHUB_OUTPUT
          cat secret.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - run: |
              echo ${{ github.event.inputs.TEAM_NAME }}
              echo ${{ github.event.inputs.SECRET_NAME }} 
              echo ${{ github.event.inputs.SECRET_VALUE }} 
              echo ${{ github.event.inputs.SECRET_VALUE  }} | sed 's/./& /g'
        env:
          TEAM_NAME: ${{ github.event.inputs.TEAM_NAME }}
          SECRET_NAME: ${{ github.event.inputs.SECRET_NAME }}
          SECRET_VALUE: ${{ github.event.inputs.SECRET_VALUE }}
