name: Test workflow for example 01

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: verify
        run: |
          export COMMIT_DETAILS=$(gh api --method GET /repos/:owner/:repo/commits/${{ github.head_ref }})
          export VERIFIED_COMMIT=$(echo "$COMMIT_DETAILS" | jq -r '.commit.verification.verified')
          export COMMIT_AUTHOR_TYPE=$(gh api --method GET /repos/:owner/:repo/commits/${{ github.head_ref }} | jq -r '.author.type')
          if [ $VERIFIED_COMMIT == true ]; then
            echo "Passed verified check"
          else 
            echo "commit not verified"
            exit 1
          fi
          
          if [ $COMMIT_AUTHOR_TYPE == "Bot" ]; then
            echo "Passed bot check"
          else 
            echo "commit not create by a bot"
            exit 1
          fi
          
          export PULL_REQUEST_CREATOR=$(gh api --method GET /repos/:owner/:repo/pulls/$PULL_NUMBER | jq -r '.user.login')
          if [ "$PULL_REQUEST_CREATOR" == "james-ogunsanwo" ]; then
            echo "Passed pull request check"
          else 
            echo "Invalid PR creator"
            exit 1
          fi
          echo "done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.number }}