name: "Check PR content"
on: 
  pull_request:

jobs:
 check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout root
      uses: actions/checkout@v3
    - run: ./.github/scripts/validate-auto-approve-pr.sh
      shell: bash
      env:
        BRANCH: ${{ github.head_ref }}
        GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
    - uses: hmarr/auto-approve-action@v0
      if: |
        github.actor == 'github-actions[bot]'
      with:
        github-token: "${{ secrets.GITHUBTOKEN }}"