name: Test workflow for example 01

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: verify
        run: |
          export VERIFIED_COMMIT=$(gh api --method GET /repos/:owner/:repo/commits/${{ github.head_ref }} | jq '.commit.verification.verified')
          if [ $VERIFIED_COMMIT == true ]; then
            echo "Passed verified check"
          else 
            echo "commit not verified"
            exit 1
          fi
          
          gh api --method GET /repos/:owner/:repo/pulls/$PULL_NUMBER | jq -r '.user.login'
          export PULL_REQUEST_CREATOR=$(gh api --method GET /repos/:owner/:repo/pulls/$PULL_NUMBER | jq -r '.user.login')
          if [ "$PULL_REQUEST_CREATOR" == "james-ogunsanwo" ]; then
            echo "pull request created by check"
          else 
            echo "Invalid PR creator"
            exit 1
          fi
          echo "done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.number }}