name: Test workflow for example 01

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: verify
        run: |
          gh api --method GET /repos/:owner/:repo/commits/release-${{ github.run_id }} | jq '.commit.verification.verified'
          
          echo "new command"
          export PULL_REQUEST_CREATOR=$(gh api --method GET /repos/:owner/:repo/pulls/$PULL_NUMBER | jq '.user.login')
          if [[ "$PULL_REQUEST_CREATOR" != "james-ogunsanwo"]]; then
            echo "Invalid PR creator"
            exit 1
          fi
          echo "success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.number }}