name: Deploy to STG

on:
  release:
    types: [prereleased]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env vars (SIT enabled)
        shell: bash
        run: |
          echo $REF
        env: 
          REF: ${{ github.ref}} 
