name: some test

on:
  release:
    types: [edited]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: do nothing
        shell: bash
        run: |
         echo "${{ github.event_name }}"
         echo "${{ github.event.action }}"