name: some test

on:
  push:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout root
      uses: actions/checkout@v3
    - name: Commit and Push
      shell: bash
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git status
        git checkout -b release-test-${{github.run_id}}
        echo targetRevision: 0.0.1 >> test-${{github.run_id}}.txt
        git add .
        git commit --allow-empty -m "testing actions"
        git pull origin main --rebase
        git push --set-upstream origin release-test-${{github.run_id}}
        gh pr create --title "Release" --body "🚦 Automerge: Enabled. " --fill
        # gh pr merge --auto --squash
      env:
        GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
