name: some test

on:
  push:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - name: checkout root
      uses: actions/checkout@v3
    - name: Commit and Push
      shell: bash
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git status
        git checkout -b release-test-${{github.run_id}}
        git commit --allow-empty -m "testing actions"
        git pull origin main --rebase
        git push --set-upstream origin release-test-${{github.run_id}}
        # gh pr create --title "Release" --body "🚦 Automerge: Enabled. " --fill
        # gh pr merge --auto --squash
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ github.token }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: release-test-${{github.run_id}}
        delete-branch: true
        title: '[Example] Update report'
        body: |
          Update report
          - 🚦 Automerge: Enabled. 
          - Auto-generated by [create-pull-request][1]
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v10
      with:
        github-token: ${{github.token}}
        bodyDoesNotContain: "Delete|this"
        bodyContains: 'Test'
        diffContains: ';'
        diffDoesNotContain: "TODO|to do"
        filesChanged: 1
        linesChanged: 1

