name: Test echo

on:
  push:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env vars (SIT enabled)
        shell: bash
        run: |
          string="A=1,B=2,C=3"
          env_vars=($(echo $string | tr "," "\n"))
          for i in ${!env_vars[@]}
          do
            echo "${env_vars[i]}" >> $GITHUB_ENV
          done
      - name: Set env vars (SIT enabled)
        shell: bash
        run: |
          echo $A
          echo $B
          echo $C