name: Test echo

on:
  push:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit changes
        shell: bash
        run: |
           INPUT_DOCKERFILE="a value"
           echo ${INPUT_DOCKERFILE}