name: Test workflow for example 01

on:
  push:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: test.txt
          DESTINATION_BRANCH: release-${{ github.run_id }}
        run: |
          git config --global user.email ""github-actions[bot]"@noreply.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b release-${{ github.run_id }}
          git pull origin main --rebase
          git push --set-upstream origin release-${{ github.run_id }}
          export TODAY=$( date -u '+%Y-%m-%d' )
          echo "$TODAY ${{ github.run_id }}" > test.txt
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
      - name: verify
        run: | 
          git rev-parse --abbrev-ref HEAD
          git log --no-decorate --show-signature -n 1
          export RETURN_VALUE="$?"
          if [ "$RETURN_VALUE" -ne 0 ]; then
            echo "PR checks are incomplete or have failed"
            exit 1
          fi
