name: Test workflow for example 01

on:
  push:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: test.txt
          DESTINATION_BRANCH: test-branch
        run: |
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          git checkout -b release-${{ github.run_id }}
          git commit --allow-empty -m "release-${{ github.run_id }}"
          git pull origin master --rebase
          git push --set-upstream origin release-${{ github.run_id }}
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
