name: Test workflow for example 01

on:
  push:
    branches: [ main, issue-* ]

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4

      - name: execute py script # run main.py
        run: python .github/scripts/01_sign_commit_using_github_api.py